### PR TITLE
Add information about Passwordless plugin

### PR DESCRIPTION
**Pull request by kucherenko**
#### By submitting this pull request, I promise that:

- [x] I have read the [contribution guidelines](https://github.com/strapi/awesome-strapi/blob/master/CONTRIBUTING.md) thoroughly.
- [x] I ensure my submission follows each and every point.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
hi @kucherenko Is this plugin for v3 or v4? We are planning to phase this repo out for tracking plugin development in favor of our upcoming marketplace and https://isstrapiready.com for plugins.

We also aren't accepting any more v3 plugins.

**Comment by kucherenko** [comment]
The plugin is for v3, v4 is WIP

**Comment by derrickmehaffy** [comment]
I'll allow this last one for v3, once you get your v4 one done you should submit it to that site I linked above and depending on the timeline you might be able to submit it to our official marketplace that is a WIP

**Review by derrickmehaffy — APPROVED** [review]
lgtm

**Pull request merged**
