### PR TITLE
[add] Scaffold, Plugin & SDK

### PR DESCRIPTION
**Pull request by TechQuery**
#### By submitting this pull request, I promise that:

- [ ] I have read the [contribution guidelines](https://github.com/strapi/awesome-strapi/blob/master/CONTRIBUTING.md) thoroughly.
- [ ] I ensure my submission follows each and every point.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
@TechQuery Looking good, let me know when you think it's ready to merge :)

**Review by derrickmehaffy — APPROVED** [review]
LGTM

**Comment by hadifarnoud** [comment]
please add RTL support to this plugin too

**Comment by TechQuery** [comment]
> please add RTL support to this plugin too

@hadifarnoud If you're talking about [strapi-plugin-ckeditor](https://github.com/TechQuery/strapi-plugin-ckeditor), you can create an Issue or Pull Request to its repository.

**Comment by derrickmehaffy** [comment]
@hadifarnoud as @TechQuery mentioned, please open an issue in it's repo.

**Pull request merged**
